In [ ]:
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [ ]:
int_to_char = dict(enumerate(alphabets))

In [ ]:
int_to_char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [ ]:
char_to_int = dict((v, i) for i, v in enumerate(alphabets))
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

Data Preparation

In [ ]:
seq_length = 1
x = []
y = []
for i in range(len(alphabets) - seq_length):
  seq_in = [alphabets[i]]
  seq_out = alphabets[i + 1]
  x += [[char_to_int[seq_in[0]]]]
  y += [char_to_int[seq_out]]
  print(seq_in, '->', seq_out)

['A'] -> B
['B'] -> C
['C'] -> D
['D'] -> E
['E'] -> F
['F'] -> G
['G'] -> H
['H'] -> I
['I'] -> J
['J'] -> K
['K'] -> L
['L'] -> M
['M'] -> N
['N'] -> O
['O'] -> P
['P'] -> Q
['Q'] -> R
['R'] -> S
['S'] -> T
['T'] -> U
['U'] -> V
['V'] -> W
['W'] -> X
['X'] -> Y
['Y'] -> Z


In [ ]:
x

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24]]

In [ ]:
y

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

Prepare the Output Variable

In [ ]:
from keras.utils import to_categorical

y_new = to_categorical(y)

In [ ]:
y_new

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

Prepare input variables

In [ ]:
import numpy as np

In [ ]:
x = np.reshape(x, (25, 1, 1))
x

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

In [ ]:
x.shape

(25, 1, 1)

In [ ]:
x_new = x / 25 # z is part of data but not the input data,  so we have to consider z too. Therefore 25.
x_new

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

In [ ]:
x_new.shape

(25, 1, 1)

Build the Model

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

In [ ]:
model = Sequential()

model.add(Dense(25, input_shape=(1, 1), activation='relu'))
model.add(LSTM(32))
model.add(Dense(26, activation='softmax'))

Compile the model

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Train the model

In [ ]:
model.fit(x_new, y_new, epochs=1000, batch_size=1)

Epoch 1/1000
25/25 [==============================] - 2s 41ms/step - loss: 1.3160 - accuracy: 0.4800
Epoch 2/1000
25/25 [==============================] - 0s 4ms/step - loss: 1.1997 - accuracy: 0.6000
Epoch 3/1000
25/25 [==============================] - 0s 5ms/step - loss: 1.1410 - accuracy: 0.6400
Epoch 4/1000
25/25 [==============================] - 0s 4ms/step - loss: 1.1285 - accuracy: 0.7200
Epoch 5/1000
25/25 [==============================] - 0s 3ms/step - loss: 1.1118 - accuracy: 0.7600
Epoch 6/1000
25/25 [==============================] - 0s 4ms/step - loss: 1.1045 - accuracy: 0.8400
Epoch 7/1000
25/25 [==============================] - 0s 5ms/step - loss: 1.0856 - accuracy: 0.8800
Epoch 8/1000
25/25 [==============================] - 0s 5ms/step - loss: 1.0819 - accuracy: 0.9200
Epoch 9/1000
25/25 [==============================] - 0s 14ms/step - loss: 1.0813 - accuracy: 0.8800
Epoch 10/1000
25/25 [==============================] - 0s 5ms/step - loss: 1.0693 - accuracy: 0.84

In [ ]:
model.evaluate(x_new, y_new, batch_size=1)

25/25 [==============================] - 1s 2ms/step - loss: 0.1975 - accuracy: 1.0000


[0.19745458662509918, 1.0]

Predict on new data

In [ ]:
val = 'K'
val_int = char_to_int[val]
val_int = np.reshape(val_int, (1, 1, 1))
val_int = val_int / 25
val_int

array([[[0.4]]])

In [ ]:
pred = model.predict(val_int)
pred

1/1 [==============================] - 1s 855ms/step


array([[5.1776367e-15, 7.7212135e-17, 1.1181500e-12, 8.0736537e-12,
        5.6200400e-10, 2.9529299e-09, 1.0577128e-08, 8.6210399e-08,
        4.3223218e-07, 1.2700062e-04, 6.1687441e-03, 9.7767442e-01,
        1.5862519e-02, 1.4793914e-04, 1.8254241e-05, 3.7021832e-07,
        1.8071542e-08, 1.7517755e-07, 5.9948257e-10, 1.6343990e-10,
        9.8542528e-12, 2.0374873e-13, 6.9599401e-15, 2.2419681e-16,
        1.6087282e-18, 1.8320504e-21]], dtype=float32)

In [ ]:
int_to_char[pred.argmax()]

'L'

In [ ]:
seq_len = 3
x = []
y = []
for i in range(len(alphabets) - seq_len):
  seq_in = alphabets[i:i + seq_len]
  seq_out = alphabets[i + seq_len]
  x.append([char_to_int[char] for char in seq_in])
  y.append(char_to_int[seq_out])
  print(seq_in, '->', seq_out)

ABC -> D
BCD -> E
CDE -> F
DEF -> G
EFG -> H
FGH -> I
GHI -> J
HIJ -> K
IJK -> L
JKL -> M
KLM -> N
LMN -> O
MNO -> P
NOP -> Q
OPQ -> R
PQR -> S
QRS -> T
RST -> U
STU -> V
TUV -> W
UVW -> X
VWX -> Y
WXY -> Z


In [ ]:
# char_to_int = dict((v, i) for i, v in enumerate(alphabets))
# char_to_int

In [ ]:
x = np.reshape(x, (len(x), seq_len, 1))
x

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 7],
        [ 8],
        [ 9]],

       [[ 8],
        [ 9],
        [10]],

       [[ 9],
        [10],
        [11]],

       [[10],
        [11],
        [12]],

       [[11],
        [12],
        [13]],

       [[12],
        [13],
        [14]],

       [[13],
        [14],
        [15]],

       [[14],
        [15],
        [16]],

       [[15],
        [16],
        [17]],

       [[16],
        [17],
        [18]],

       [[17],
        [18],
        [19]],

       [[18],
        [19],
        [20]],

       [[19],
        [20],
        [21]],

       [[20],
        [21],
        [22]],

       [[21],
        [22],
        [23]],

       [[22],
        [23],
    

In [ ]:
x.shape

(23, 3, 1)

In [ ]:
x = x / 25

In [ ]:
model = Sequential()

model.add(Dense(25, input_shape=(3, 1), activation='relu'))
model.add(LSTM(128))
model.add(Dense(26, activation='softmax'))

In [ ]:
y_new = to_categorical(y)
y_new.shape

(23, 26)

In [ ]:
y_new

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [ ]:
# compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# train the model
model.fit(x, y_new, epochs=1000, batch_size=1)

Epoch 1/1000
23/23 [==============================] - 3s 30ms/step - loss: 3.2774 - accuracy: 0.0000e+00
Epoch 2/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.2469 - accuracy: 0.0435
Epoch 3/1000
23/23 [==============================] - 0s 4ms/step - loss: 3.2267 - accuracy: 0.0435
Epoch 4/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.2048 - accuracy: 0.0435
Epoch 5/1000
23/23 [==============================] - 0s 5ms/step - loss: 3.1686 - accuracy: 0.0435
Epoch 6/1000
23/23 [==============================] - 0s 7ms/step - loss: 3.1244 - accuracy: 0.0435
Epoch 7/1000
23/23 [==============================] - 2s 72ms/step - loss: 3.0792 - accuracy: 0.0435
Epoch 8/1000
23/23 [==============================] - 0s 4ms/step - loss: 3.0246 - accuracy: 0.0000e+00
Epoch 9/1000
23/23 [==============================] - 0s 5ms/step - loss: 2.9911 - accuracy: 0.0870
Epoch 10/1000
23/23 [==============================] - 0s 6ms/step - loss: 2.9270 - accura

In [ ]:
model.evaluate(x, y_new, batch_size=1)

23/23 [==============================] - 1s 32ms/step - loss: 0.0145 - accuracy: 1.0000


[0.0145339360460639, 1.0]

Predict on new sequence

In [ ]:
new = 'EFG'
new = np.array([[char_to_int[x]] for x in new])
print(new)
new = new.reshape(1, 3, 1)
new = new / 25
pred = model.predict(new)
pred = np.argmax(pred)
op = int_to_char[pred]
op

[[4]
 [5]
 [6]]
1/1 [==============================] - 0s 325ms/step


'H'

Predict the character in a sequence

In [ ]:
new = 'ABC'
new = char_to_int[new]
new = np.reshape(new, (1, 1, 1))
new = new / 25
pred = model.predict(new)
pred = np.argmax(pred)
int_to_char[pred]

KeyError: 'ABC'